### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by nanuxbe**
Nothing actually working yet but this should get us started. This PR provides:
- A basic structure for components (without actions so far) largely inspired by Django Forms
- A base sample application with models/admin/api
  - CookBook (a user has many cookbooks)
  - Recipe (a cookbook has many recipes)
  - Following (users can follow each other)
- A list (classic GCBV) of users in the sample application to link to the different implementations of profiles (GitHub style profiles but with cookbooks and recipes instead)

Sorry for the _huge_ PR, a lot of it is actually assets for the sample application (can someone review and accept/reject it please). The most interesting files to review are actually in `toga_web/components`

### CODE REVIEW

**Comment by Psykopear** [comment]
Hi Emma! You are right this PR is huge, and it's not very easy to make a review in this state. 
I think it would be great if we could have a smaller PR with only the component's structure and maybe add the example in a latter PR. 
This way I can review the first structure's stub, and when this will be ready we can actually try and review the example too.
I think this will make it easier to have clean code thanks to the fact that we can review the PR with more accuracy.

That said, thank you for the big work you have done untill now. I should be able to make the review for this weekend/the beginning of the next week :)

**Comment by Psykopear** [comment]
Maybe we could start by creating some "atomic" issues and have each PR try to solve a single one, this way we can parallelize the work and have a sort of roadmap to help everybody focus on the next goal. 
If you'd like we can plan a meeting on the djangounderthehood slack channel (or somewhere else it's ok) for the next week so we can share ideas on how to organize the project and how to work together in the best way.

**Comment by nanuxbe** [comment]
This PR doesn't actually solve anything (except for the missing .gitignore issue) it just lays the tiles for more work.
The most important things to review (eg the actual application) is in commits ab04200 & 3e3ba69

The sample application "usefull" things are in commit 30b73c9. The homepage, which doesn't do much so far, is created in 2a6f850 which is bigger since it also adds bootstrap sass source files (unmodified but I believe they need to be included as I don't know of any package containing bootstrap source which can be included instead).The rest being mostly styling (it's not because it's a sample app that it should look ugly).

As for the atomic PR for the future I totally agree, I was thinking about starting with 4 issues, each one being "create a working implementation for framework XXX". The different "frameworks" being the ones we talked about "pure django", react (+ something, probably request, to query the api), angular and ember.
The ember implementation being a slightly bit different as is doesn't produce any html and could probably be used for iOS, Android or any other stand-alone client.
And the django implementation being a slightly bit different as well since it will query the api internally (using a special drf renderer).

I think the implementations should extend the base components defined in `components/base.py` and be located in `components/xxx.py`

Those PR's would allow to validate the current base `Component` classes and see if they are usable by all the implementations (since they don't actually do anything, it's kinda hard to write any meaningful test thus far)

**Comment by Psykopear** [comment]
Ok, I cloned the repo and looked through the code. 

The code for the components backend can be a good point to start with. 

The main problem here is the project management. 
Being an open source project with more people collaborating in it, we should try to make it possible for other people to work with our code, we should have a clear roadmap and try to keep the project as cleen and simple as possible. 

About the code, as I said it can be good, but I think this is something that should be done following a test driven development, as when the project will start to grow and get more complex it will become unmantainable otherwise.

It's ok to have working examples, but that's not the first thing to do in my opinion, and I wouldn't start to add those until there is a good and tested stub of the backend (but again that's my way of doing things, I can be wrong).

That said, if you'd like I can try to start from the code you already wrote and cleanup what I think is not needed and write tests for what is already there. Anyway if you and the other contributors agree that this pull request is ok and that should be the starting point I guess I can call me out from the project as I wouldn't be comfortable working this way.

**Comment by nanuxbe** [comment]
>  The code for the components backend can be a good point to start with.

This is what I was aiming for, so I guess that's good :smile:

> The main problem here is the project management. 
> Being an open source project with more people collaborating in it, we should try to make it possible for other people to work with our code, we should have a clear roadmap and try to keep the project as cleen and simple as possible.

I realize that you missed most of what we talked about during the sprints at DUTH, so I created a [wiki page](https://github.com/nanuxbe/toga_web/wiki) to try to summarize what has been discussed ( @jrief & @freakboy3742 could you make sure I didn't forget anything?).

I've also created [another wiki page](https://github.com/nanuxbe/toga_web/wiki/Ideas-and-examples) with some of the use-cases which have been talked about (right now those are just mine, I know @freakboy3742 has at least another one but I'd rather have him post it if he feels comfortable with it as it's his application)

I hope this will make things clearer to you in regards of where we are comming from and going to with this project. But to be blunt, the only roadmap right now is to get a working MVP.

> About the code, as I said it can be good, but I think this is something that should be done following a test driven development, as when the project will start to grow and get more complex it will become unmantainable otherwise.

Personnaly I don't see how we could use TDD at this stage of the project for several reasons:
- We had a clear idea of what we want to achieve but are not sure how to get there yet. Using TDD will just let us have a bunch of failing test which will most likely have to be re-written in the end because they do not correspond to what we have actually built.
- I personally know EmberJS and am willing to dabble with React+Flux to validate that our approach works but I have very little knowledge of Angular or DRF custom renderers (@jrief does) and although I believe an implementation that would work for EmberJS will also work for other independent frontends (like iOS/Android apps), this will only be validated by actually plugging in a real app (maybe Toga) into this backend we will not know for certain.

So if you have extensive knowledge in all the previously mentioned technologies and are sure that you know what has to be achieved to in order to produce something that will be pluggable into each and everyone of those solutions, please do write the tests and we will work at making them pass.

If you don't, well I guess that the way to go is to put all our knowledge together at building to see how we can achieve "connectivity" to every one of these frontends while trying to stick to the syntax we have defined and modifying what has to be changed as we move forward.

Once we'll have a definitive architecture and know exactly what has to be done, then the first thing to do will be to write lots of tests.

> It's ok to have working examples, but that's not the first thing to do in my opinion, and I wouldn't start to add those until there is a good and tested stub of the backend (but again that's my way of doing things, I can be wrong).

Once again, if you have the necessary knowledge to know exactly what the targeted frontends will need in order to talk to the backend, please write those tests. Personally I don't and I know that other people involved in this project don't either so I do feel that a working sample app is pretty usefull.

> That said, if you'd like I can try to start from the code you already wrote and cleanup what I think is not needed and write tests for what is already there. Anyway if you and the other contributors agree that this pull request is ok and that should be the starting point I guess I can call me out from the project as I wouldn't be comfortable working this way.

If by cleaning up you mean that my code is messy and you'd like to improve it: go ahead, this is what code reviews are made for.

But if by cleaning up you mean removing the sample application, COC or other files you deem unnecessary, I really don't like to work for nothing and everything I did commit here is there because I deem it necessary. So, please don't.

By the long exchanges on this PR, it sounds like we do have very different approaches on how to handle this project. But the if we want to see this going anywhere, maybe we should stop talking and start working, so unless someone tells me I have written horrible code or made a huge mistake somewhere in the code and it should be fixed, I'll accept this PR at the end of the weekend and move forward with either an Ember (most likely) or a React implementation.

On your side, if you feel that there are some tests which can already be written, please do so and let's move forward.

Cheers,
Emma

**Comment by Psykopear** [comment]
Please don't take it personally, I didn't discuss the quality of the code here, neither I said I have a great and wide knowledge of frontends framework, I'm in fact just a backend developer. 

As you said, we have very different approaches on how to handle projects, and that's the point.

I just wanted to be as direct as possible at this stage to understand where this was going, didn't mean to be rude, and I'm sorry if it sounded this way, sometimes it's not easy to be both clear and kind.

Bests,
Federico

**Pull request merged**
